# Generated by Django 2.2.6 on 2019-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=50)),
                ('invoice', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(upload_to='photos')),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=835215)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
