# Generated by Django 2.2.6 on 2019-10-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('invoice', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='')),
                ('ref', models.CharField(default='-', max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('accs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Acc')),
            ],
        ),
    ]
