# Generated by Django 2.2.6 on 2019-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='invoice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ref',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
