# Generated by Django 2.2.6 on 2019-10-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191021_1954'),
        ('listings', '0002_auto_20191021_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Acc'),
        ),
    ]
