# Generated by Django 2.2.6 on 2019-10-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='acc',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Acc'),
        ),
    ]
