# Generated by Django 2.2.6 on 2019-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20191021_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='acc',
        ),
    ]
