# Generated by Django 2.2.6 on 2019-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_accs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
