# Generated by Django 2.2.6 on 2019-10-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20191022_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo',
            new_name='pic',
        ),
    ]
