# Generated by Django 2.2.6 on 2019-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('acc', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('bname', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('isgov', models.BooleanField(default=False)),
            ],
        ),
    ]
