# Generated by Django 2.2.6 on 2019-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='acc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='acc',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='acc',
            name='bname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='acc',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='acc',
            name='pin',
            field=models.IntegerField(default=835215),
        ),
    ]
